image:
  books: 
    repository: seven02/emart_javaapi
    tag: latest
  main: 
    repository: seven02/emart_nodeapi
    tag: latest
service:
  books:
    port: 9000
    type: NodePort
  main:
    port: 5000
    type: NodePort
ingress:
  host: nerdydreams.com.ng
  path:
    main: /api
    books: /webapi
