apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-books
  labels: 
    app: {{ .Chart.Name }}-books
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-books
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-books
    spec:
      containers:
      - name: {{ .Chart.Name }}-books
        image: {{ .Values.image.books.repository }}:{{ .Values.image.books.tag }}
        imagePullPolicy: Always
        ports:
        - name: ebooksapi-port
          containerPort: 9000
        env: 
         - name: MONGOURI
           value: 'mongodb://emongo:27017/epoc'
         - name: SECRETORKEY
           value: 'k1234e6s78h9av'
#      imagePullSecrets:
#      - name: regcred 
     
