apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-main
  labels: 
    app: {{ .Chart.Name }}-main
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-main
    spec:
      containers:
      - name: {{ .Chart.Name }}-main
        image: {{ .Values.image.main.repository }}:{{ .Values.image.main.tag }}
        imagePullPolicy: Always
        ports:
        - name: enodeapi-port
          containerPort: 5000
#      imagePullSecrets:
#      - name: regcred 
     
