apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-books
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.books.port }}
    targetPort: ebooksapi-port
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-books
  type: {{ .Values.service.books.type }}
