apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-main
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.main.port }}
    targetPort: enodeapi-port
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-main
  type: {{ .Values.service.main.type }}
