---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-mongo
  namespace: {{ .Values.namespace }} 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local 
  resources:
    requests:
      storage: 500Mi
