---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-mongo 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local 
  resources:
    requests:
      storage: 500Mi
