apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-mongo
  labels:
    app: {{ .Chart.Name }}-mongo
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mongo
    spec:
      containers:
      - name: {{ .Chart.Name }}-mongo
        image: {{ .Values.image.mongo.repository }}:{{ .Values.image.mongo.tag }}
        ports:
        - name: emongodb-port
          containerPort: 27017
        volumeMounts:
            - name: {{ .Chart.Name }}-mongo
              mountPath: /data/db
        env: 
         - name: MONGO_INITDB_DATABASE
           valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-dbconfig
              key: mongodbname
    
      volumes:
      - name: {{ .Chart.Name }}-mongo
        emptyDir: {}

