apiVersion: v1
kind: Service
metadata:
  name: emongo
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.mongo.port }}
    targetPort: 27017
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-mongo
  type: {{ .Values.service.mongo.type }}
