image:
  client:
    repository: seven02/emart_client
    tag: latest
service:
  client:
    port: 4200
    type: NodePort #this would be LoadBalancer if it's on a cloud provider tha provisions one
ingress:
  host: nerdydreams.com.ng
  path:
    client: /
namespace: ingress-nginx
