apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-client
  labels: 
    app: {{ .Chart.Name }}-client
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-client
    spec:
      containers:
      - name: {{ .Chart.Name }}-client
        image: {{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}
        imagePullPolicy: Always
        ports:
        - name: eclient-port
          containerPort: 4200
#      imagePullSecrets:
#      - name: regcred 
     
