apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-client
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.client.port }}
    targetPort: eclient-port
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-client
  type: {{ .Values.service.client.type }}
